apiVersion: v1
items:
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfigPool
  metadata:
    creationTimestamp: "2024-08-05T16:24:47Z"
    generation: 2
    labels:
      machineconfiguration.openshift.io/mco-built-in: ""
      operator.machineconfiguration.openshift.io/required-for-upgrade: ""
      pools.operator.machineconfiguration.openshift.io/master: ""
    name: master
    resourceVersion: "21544"
    uid: dcbc177a-a38c-4be1-a3fa-d4020ac58c5c
  spec:
    configuration:
      name: rendered-master-f898aa7d05f995ca972f6930b43c6b5b
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-master
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-ssh
    machineConfigSelector:
      matchLabels:
        machineconfiguration.openshift.io/role: master
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
    paused: false
  status:
    certExpirys:
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-08-03T16:10:52Z"
      subject: CN=admin-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-08-06T16:10:54Z"
      subject: CN=kube-csr-signer_@1722875040
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-08-06T16:10:54Z"
      subject: CN=kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-08-05T16:10:55Z"
      subject: CN=kube-apiserver-to-kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-08-05T16:10:54Z"
      subject: CN=kube-control-plane-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-08-03T16:10:53Z"
      subject: CN=kubelet-bootstrap-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-08-05T16:24:01Z"
      subject: CN=openshift-kube-apiserver-operator_node-system-admin-signer@1722875041
    conditions:
    - lastTransitionTime: "2024-08-05T16:25:00Z"
      message: ""
      reason: ""
      status: "False"
      type: RenderDegraded
    - lastTransitionTime: "2024-08-05T16:29:25Z"
      message: All nodes are updated with MachineConfig rendered-master-f898aa7d05f995ca972f6930b43c6b5b
      reason: ""
      status: "True"
      type: Updated
    - lastTransitionTime: "2024-08-05T16:29:25Z"
      message: ""
      reason: ""
      status: "False"
      type: Updating
    - lastTransitionTime: "2024-08-05T16:29:25Z"
      message: ""
      reason: ""
      status: "False"
      type: NodeDegraded
    - lastTransitionTime: "2024-08-05T16:29:25Z"
      message: ""
      reason: ""
      status: "False"
      type: Degraded
    configuration:
      name: rendered-master-f898aa7d05f995ca972f6930b43c6b5b
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-master
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-ssh
    degradedMachineCount: 0
    machineCount: 3
    observedGeneration: 2
    readyMachineCount: 3
    unavailableMachineCount: 0
    updatedMachineCount: 3
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfigPool
  metadata:
    creationTimestamp: "2024-08-05T16:24:47Z"
    generation: 2
    labels:
      machineconfiguration.openshift.io/mco-built-in: ""
      pools.operator.machineconfiguration.openshift.io/worker: ""
    name: worker
    resourceVersion: "21545"
    uid: 7db21ea2-9955-4ad9-b872-e7c797211c55
  spec:
    configuration:
      name: rendered-worker-2a854b4a0c86cb8484ee1697c7d0686c
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-worker
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-ssh
    machineConfigSelector:
      matchLabels:
        machineconfiguration.openshift.io/role: worker
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
    paused: false
  status:
    certExpirys:
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-08-03T16:10:52Z"
      subject: CN=admin-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-08-06T16:10:54Z"
      subject: CN=kube-csr-signer_@1722875040
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-08-06T16:10:54Z"
      subject: CN=kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-08-05T16:10:55Z"
      subject: CN=kube-apiserver-to-kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-08-05T16:10:54Z"
      subject: CN=kube-control-plane-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-08-03T16:10:53Z"
      subject: CN=kubelet-bootstrap-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-08-05T16:24:01Z"
      subject: CN=openshift-kube-apiserver-operator_node-system-admin-signer@1722875041
    conditions:
    - lastTransitionTime: "2024-08-05T16:25:00Z"
      message: ""
      reason: ""
      status: "False"
      type: RenderDegraded
    - lastTransitionTime: "2024-08-05T16:25:04Z"
      message: All nodes are updated with MachineConfig rendered-worker-2a854b4a0c86cb8484ee1697c7d0686c
      reason: ""
      status: "True"
      type: Updated
    - lastTransitionTime: "2024-08-05T16:25:04Z"
      message: ""
      reason: ""
      status: "False"
      type: Updating
    - lastTransitionTime: "2024-08-05T16:25:04Z"
      message: ""
      reason: ""
      status: "False"
      type: NodeDegraded
    - lastTransitionTime: "2024-08-05T16:25:04Z"
      message: ""
      reason: ""
      status: "False"
      type: Degraded
    configuration:
      name: rendered-worker-2a854b4a0c86cb8484ee1697c7d0686c
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-worker
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-ssh
    degradedMachineCount: 0
    machineCount: 0
    observedGeneration: 2
    readyMachineCount: 0
    unavailableMachineCount: 0
    updatedMachineCount: 0
kind: List
metadata:
  resourceVersion: ""
