apiVersion: v1
items:
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfigPool
  metadata:
    creationTimestamp: "2024-12-10T17:51:19Z"
    generation: 4
    labels:
      machineconfiguration.openshift.io/mco-built-in: ""
      operator.machineconfiguration.openshift.io/required-for-upgrade: ""
      pools.operator.machineconfiguration.openshift.io/master: ""
    name: master
    resourceVersion: "61138"
    uid: e32e6a57-23d1-4f57-8816-1c159f4cb679
  spec:
    configuration:
      name: rendered-master-ea25e5fddbcf61a41465f574f4904b6c
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-master
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-ssh
    machineConfigSelector:
      matchLabels:
        machineconfiguration.openshift.io/role: master
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""
    paused: false
  status:
    certExpirys:
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-12-08T17:37:37Z"
      subject: CN=admin-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-12-11T17:37:40Z"
      subject: CN=kube-csr-signer_@1733853031
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-12-11T17:37:40Z"
      subject: CN=kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-12-10T17:37:40Z"
      subject: CN=kube-apiserver-to-kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-12-10T17:37:40Z"
      subject: CN=kube-control-plane-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-12-08T17:37:38Z"
      subject: CN=kubelet-bootstrap-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-12-10T17:50:30Z"
      subject: CN=openshift-kube-apiserver-operator_node-system-admin-signer@1733853030
    conditions:
    - lastTransitionTime: "2024-12-10T17:51:39Z"
      message: ""
      reason: ""
      status: "False"
      type: RenderDegraded
    - lastTransitionTime: "2024-12-10T17:51:44Z"
      message: ""
      reason: ""
      status: "False"
      type: NodeDegraded
    - lastTransitionTime: "2024-12-10T17:51:44Z"
      message: ""
      reason: ""
      status: "False"
      type: Degraded
    - lastTransitionTime: "2024-12-10T18:43:15Z"
      message: All nodes are updated with MachineConfig rendered-master-ea25e5fddbcf61a41465f574f4904b6c
      reason: ""
      status: "True"
      type: Updated
    - lastTransitionTime: "2024-12-10T18:43:15Z"
      message: ""
      reason: ""
      status: "False"
      type: Updating
    configuration:
      name: rendered-master-ea25e5fddbcf61a41465f574f4904b6c
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-master
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-master-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-master-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-master-ssh
    degradedMachineCount: 0
    machineCount: 3
    observedGeneration: 4
    readyMachineCount: 3
    unavailableMachineCount: 0
    updatedMachineCount: 3
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfigPool
  metadata:
    creationTimestamp: "2024-12-10T17:51:19Z"
    generation: 5
    labels:
      machineconfiguration.openshift.io/mco-built-in: ""
      pools.operator.machineconfiguration.openshift.io/worker: ""
    name: worker
    resourceVersion: "61903"
    uid: 3b60de2a-2acc-4e3d-822c-d5414d25fcbc
  spec:
    configuration:
      name: rendered-worker-79d8de7d658c5145794418295a4ac563
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-worker
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-realtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-ssh
    machineConfigSelector:
      matchLabels:
        machineconfiguration.openshift.io/role: worker
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
    paused: false
  status:
    certExpirys:
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-12-08T17:37:37Z"
      subject: CN=admin-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-12-11T17:37:40Z"
      subject: CN=kube-csr-signer_@1733853031
    - bundle: KubeAPIServerServingCAData
      expiry: "2024-12-11T17:37:40Z"
      subject: CN=kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-12-10T17:37:40Z"
      subject: CN=kube-apiserver-to-kubelet-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-12-10T17:37:40Z"
      subject: CN=kube-control-plane-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2034-12-08T17:37:38Z"
      subject: CN=kubelet-bootstrap-kubeconfig-signer,OU=openshift
    - bundle: KubeAPIServerServingCAData
      expiry: "2025-12-10T17:50:30Z"
      subject: CN=openshift-kube-apiserver-operator_node-system-admin-signer@1733853030
    conditions:
    - lastTransitionTime: "2024-12-10T17:51:39Z"
      message: ""
      reason: ""
      status: "False"
      type: RenderDegraded
    - lastTransitionTime: "2024-12-10T17:51:44Z"
      message: ""
      reason: ""
      status: "False"
      type: NodeDegraded
    - lastTransitionTime: "2024-12-10T17:51:44Z"
      message: ""
      reason: ""
      status: "False"
      type: Degraded
    - lastTransitionTime: "2024-12-10T18:45:13Z"
      message: ""
      reason: ""
      status: "False"
      type: Updated
    - lastTransitionTime: "2024-12-10T18:45:13Z"
      message: All nodes are updating to MachineConfig rendered-worker-79d8de7d658c5145794418295a4ac563
      reason: ""
      status: "True"
      type: Updating
    configuration:
      name: rendered-worker-4af5b23969279574c43a380cf0d3a0d6
      source:
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 00-worker
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-container-runtime
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 01-worker-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 97-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 98-worker-generated-kubelet
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-generated-registries
      - apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        name: 99-worker-ssh
    degradedMachineCount: 0
    machineCount: 3
    observedGeneration: 5
    readyMachineCount: 0
    unavailableMachineCount: 1
    updatedMachineCount: 0
kind: List
metadata:
  resourceVersion: ""
