apiVersion: config.openshift.io/v1
kind: Infrastructure
metadata:
  creationTimestamp: "2026-08-11T15:31:29Z"
  generation: 1
  name: cluster
  resourceVersion: "584"
  uid: eca05796-c1eb-4ca5-abda-542bfdb83987
spec:
  cloudConfig:
    key: config
    name: cloud-provider-config
  platformSpec:
    type: GCP
status:
  apiServerInternalURI: https://api-int.ci-ln-bnrthzt-72292.gcp-2.ci.openshift.org:6443
  apiServerURL: https://api.ci-ln-bnrthzt-72292.gcp-2.ci.openshift.org:6443
  controlPlaneTopology: HighlyAvailable
  cpuPartitioning: None
  etcdDiscoveryDomain: ""
  infrastructureName: ci-ln-bnrthzt-72292-k9qtk
  infrastructureTopology: HighlyAvailable
  platform: GCP
  platformStatus:
    gcp:
      cloudLoadBalancerConfig:
        dnsType: PlatformDefault
      projectID: openshift-gce-devel-ci-2
      region: us-central1
    type: GCP
