apiVersion: v1
kind: Pod
metadata:
  generateName: restart-kubelet-pod-
spec:
  restartPolicy: Never
  hostPID: true
  containers:
    - command:
        - /bin/bash
        - -c
      image: registry.redhat.io/openshift4/ose-must-gather:latest
      name: restart-kubelet
      terminationMessagePolicy: FallbackToLogsOnError
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /host-root
        name: host-root
      - name: source-data
        mountPath: "/source-data"
        readOnly: true
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
  - name: source-data
    secret:
      secretName: source-data